language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - 'hhvm'

matrix:
allow_failures:
    - php: hhvm

before_script:
    - npm install
script:
    - npm run test

env:
  global:
    - GH_REF: bem/bem-components-php
